name: test
on:
  push:
    branches: [ci-test]
permissions:
  contents: write
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ANDROID_HOME=$ANDROID_HOME"; ls $ANDROID_HOME/platforms | tail -3; ls $ANDROID_HOME/build-tools | tail -3; java -version 2>&1 | head -1; which gradle && gradle --version | head -3
